import { useEffect, useState } from 'react'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowRight, Check, Menu, Play, ShieldCheck, Smartphone, X, Zap } from 'lucide-react'
import './App.css'

const nav = [
  { label: 'Home', to: '/' },
  { label: 'About Us', to: '/about' },
  { label: 'Services', to: '/services' },
  { label: 'Pricing', to: '/pricing' },
  { label: 'Contact Us', to: '/contact' },
]

const features = [
  { icon: Zap, title: 'Fast & Reliable', text: 'Move money in seconds with a platform built for modern business.' },
  { icon: ShieldCheck, title: 'Bank-grade security', text: 'Your money and data are protected with layers of smart security.' },
  { icon: Smartphone, title: 'Built for everyone', text: 'Simple tools for individuals, businesses, and growing teams.' },
]

function Header() {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  useEffect(() => setOpen(false), [location.pathname])
  return <header className="site-header"><div className="container nav-wrap">
    <Link to="/" className="logo"><span className="logo-mark">t</span><span>tula<span className="logo-accent">pay</span></span></Link>
    <nav className={open ? 'nav-links open' : 'nav-links'}>{nav.map(item => <NavLink key={item.to} to={item.to} className={({isActive}) => isActive ? 'active' : ''}>{item.label}</NavLink>)}<Link className="nav-cta" to="/contact">Get Started <ArrowRight size={16}/></Link></nav>
    <button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X/> : <Menu/>}</button>
  </div></header>
}

function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Link to="/" className="logo footer-logo"><span className="logo-mark">t</span><span>tula<span className="logo-accent">pay</span></span></Link><p>Powering simple, secure payments for Africa and beyond.</p><div className="socials"><a href="#" aria-label="Twitter"><span>𝕏</span></a><a href="#" aria-label="LinkedIn"><span>in</span></a><a href="#" aria-label="Instagram"><span>ig</span></a><a href="#" aria-label="Facebook"><span>f</span></a></div></div><div><h4>Company</h4><Link to="/about">About Us</Link><Link to="/services">Services</Link><Link to="/pricing">Pricing</Link></div><div><h4>Support</h4><Link to="/contact">Contact Us</Link><a href="#faq">FAQs</a><a href="#">Privacy Policy</a></div><div><h4>Stay in the loop</h4><p>Get product news and useful insights.</p><div className="newsletter"><input placeholder="Your email address" aria-label="Email address"/><button aria-label="Subscribe"><ArrowRight size={18}/></button></div></div></div><div className="container footer-bottom"><span>© 2026 TulaPay. All rights reserved.</span><span>Made for progress.</span></div></footer> }

function ScrollReveal({children, className='' }: {children: React.ReactNode, className?: string}) { return <div className={`reveal ${className}`}>{children}</div> }

function Hero() { return <section className="hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> The future of payments is here</div><h1>Payments made <em>simple.</em><br/>Possibilities made <em>real.</em></h1><p>At TulaPay, we make it easy for people and businesses to move, manage, and grow their money with confidence.</p><div className="hero-actions"><Link to="/contact" className="button primary">Get started <ArrowRight size={18}/></Link><a href="#story" className="button ghost"><span className="play"><Play size={12} fill="currentColor"/></span> See how it works</a></div><div className="hero-proof"><div className="avatars"><span>JM</span><span>AK</span><span>NF</span><b>+</b></div><div><strong>Trusted by 10,000+</strong><small>people and businesses</small></div></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="phone-card"><div className="card-top"><span className="mini-logo">t</span><span>•••</span></div><small>Available balance</small><strong>₦ 2,450,000<span>.00</span></strong><div className="card-chip"><span>●</span><span>●</span><span>●</span><span>●</span><b>VISA</b></div></div><div className="float-card transfer"><span className="float-icon green"><ArrowRight size={16}/></span><div><small>Money received</small><strong>+ ₦85,000.00</strong></div><Check className="float-check" size={16}/></div><div className="float-card security"><span className="float-icon purple"><ShieldCheck size={16}/></span><div><small>Protected by TulaPay</small><strong>Secure payment</strong></div></div></div></div><div className="hero-curve"/></section> }

function Stats() { return <section className="stats"><div className="container stats-grid"><div><strong>₦2.4B+</strong><span>Transactions processed</span></div><div><strong>10K+</strong><span>Happy customers</span></div><div><strong>99.9%</strong><span>Platform uptime</span></div><div><strong>24/7</strong><span>Support when you need it</span></div></div></section> }

function Home() { return <><Hero/><Stats/><section className="section intro" id="story"><ScrollReveal><div className="section-label">Why TulaPay</div><h2>One platform.<br/><span>Every possibility.</span></h2></ScrollReveal><ScrollReveal className="intro-right"><p>Whether you're sending money to family, paying for everyday needs, or building the next big business, TulaPay gives you the tools to make it happen.</p><Link to="/about" className="text-link">Discover our story <ArrowRight size={17}/></Link></ScrollReveal></section><section className="section feature-section"><div className="section-heading"><div><div className="section-label">Made for your momentum</div><h2>Everything you need<br/>to move <span>forward.</span></h2></div><p>From your first payment to your next million, we've got you covered.</p></div><div className="feature-grid">{features.map(({icon:Icon,title,text}) => <ScrollReveal key={title} className="feature-card"><div className="feature-icon"><Icon size={23}/></div><h3>{title}</h3><p>{text}</p><ArrowRight className="card-arrow" size={18}/></ScrollReveal>)}</div></section><section className="cta-band"><div className="container cta-content"><div><div className="section-label light">Ready when you are</div><h2>Let&apos;s make money<br/><em>move.</em></h2></div><Link to="/contact" className="button light-button">Get started today <ArrowRight size={18}/></Link></div></section></> }

function PageHero({label,title,sub}: {label:string,title:React.ReactNode,sub:string}) { return <section className="page-hero"><div className="container"><div className="section-label">{label}</div><h1>{title}</h1><p>{sub}</p></div></section> }
function About() { return <><PageHero label="Our story" title={<>Built to make<br/><em>progress possible.</em></>} sub="TulaPay is creating a more connected financial future, one simple experience at a time."/><section className="section about-content"><div className="about-stat"><strong>01</strong><span>Our mission</span></div><div><h2>Finance shouldn&apos;t be<br/><span>complicated.</span></h2><p>We believe everyone deserves access to financial tools that are clear, inclusive, and built around real life. TulaPay brings payments, transfers, and financial services together in one trusted place.</p><p>We&apos;re building the infrastructure for a world where money moves as freely as ideas do.</p></div></section><section className="values"><div className="container"><div className="section-label">What guides us</div><div className="values-grid">{['Keep it simple','Build with trust','Think beyond today'].map((x,i)=><div className="value" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{['Clarity is a feature. We remove friction from every experience.','We earn confidence through security, transparency, and consistency.','We are building for the future, not just the next transaction.'][i]}</p></div>)}</div></div></section></> }
function Services() { return <><PageHero label="What we do" title={<>The tools to<br/><em>move forward.</em></>} sub="Simple, powerful financial services designed around the way you live and work."/><section className="section services-list">{[['01','Payments','Pay bills, shop online, and handle everyday expenses with ease.'],['02','Send money','Move money to friends, family, and partners quickly and securely.'],['03','Business tools','Power your business with seamless collections and smart financial tools.'],['04','TulaPay card','A card that puts your money within reach, wherever life takes you.']].map(([num,title,text])=><div className="service-row" key={title}><span>{num}</span><h2>{title}</h2><p>{text}</p><ArrowRight/></div>)}</section></> }
function Pricing() { return <><PageHero label="Simple pricing" title={<>More value.<br/><em>Less friction.</em></>} sub="Transparent pricing that works for you, whether you're getting started or scaling up."/><section className="section pricing-grid">{[['Personal','For everyday money movement','Free','No monthly fees','Send and receive money','Pay bills and subscriptions'],['Business','For ambitious businesses','Custom','Built around your needs','Payment collections','Business dashboard and insights']].map(([name,desc,price,...items],i)=><div className={`price-card ${i===1?'featured':''}`} key={name}>{i===1&&<span className="popular">Most popular</span>}<div className="section-label">{name}</div><p>{desc}</p><div className="price">{price}{price==='Free'&&<small> forever</small>}</div>{items.map(item=><div className="check-row" key={item}><Check size={16}/>{item}</div>)}<Link to="/contact" className={`button ${i===1?'primary':'outline'}`}>Get started <ArrowRight size={17}/></Link></div>)}</section></> }
function Contact() { const [sent,setSent]=useState(false); return <><PageHero label="Say hello" title={<>Let&apos;s start<br/><em>something good.</em></>} sub="Have a question, an idea, or just want to talk? Our team is here for you."/><section className="section contact-grid"><div><h2>We&apos;d love to<br/><span>hear from you.</span></h2><p>Fill in the form and someone from our team will get back to you as soon as possible.</p><div className="contact-details"><div><small>Email us</small><strong>hello@tulapay.ai</strong></div><div><small>Follow along</small><strong>@tulapay</strong></div></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><Check size={30}/><h3>Message received.</h3><p>Thanks for reaching out. We&apos;ll be in touch soon.</p></div>:<><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>How can we help?<textarea required rows={5} placeholder="Tell us a little about your question..."/></label><button className="button primary" type="submit">Send message <ArrowRight size={18}/></button></>}</form></section></> }
function NotFound(){return <div className="not-found"><div className="section-label">Page not found</div><h1>Looks like this<br/><em>page moved.</em></h1><Link to="/" className="button primary">Back home <ArrowRight size={18}/></Link></div>}
function App(){return <BrowserRouter><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/pricing" element={<Pricing/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></BrowserRouter>}
export default App
